# generated by datamodel-codegen:
#   filename:  Entity.json
#   timestamp: 2022-11-20T14:01:46+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel, Field


class LangCode(Enum):
    en = 'en'
    de = 'de'


class KBEntityFooter(BaseModel):
    osl_template: Optional[str] = 'OslTemplate:KB/Entity/Footer'


class Entity(BaseModel):
    osl_template: Optional[str] = 'OslTemplate:KB/Entity'
    osl_template_label: Optional[str] = 'Entity'
    label: Optional[Union[str, List[str]]] = Field(None, title='Label')
    """
    Human readable name
    """
    label_lang_code: Optional[LangCode] = Field('en', title='Lang code')
    extensions: Optional[List[Any]] = Field(None, title='Extensions')
    osl_wikitext: Optional[str] = '=Details=\n'
    osl_footer: Optional[KBEntityFooter] = Field(
        {'osl_template': 'OslTemplate:KB/Entity/Footer'}, title='KB/Entity/Footer'
    )
