# generated by datamodel-codegen:
#   filename:  Entity.json
#   timestamp: 2022-11-20T14:44:08+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field


class LangCode(Enum):
    en = 'en'
    de = 'de'


class KBEntityFooter(BaseModel):
    osl_template: Optional[str] = 'OslTemplate:KB/Entity/Footer'


class LIMSDeviceFooter(BaseModel):
    osl_template: Optional[str] = 'OslTemplate:LIMS/Device/Footer'


class Device(BaseModel):
    osl_template: Optional[str] = 'OslTemplate:LIMS/Device'
    osl_template_label: Optional[str] = 'Device'
    manufacturer: Optional[str] = Field(None, title='Manufacturer')
    extensions: Optional[List[Device]] = Field(None, title='Extensions')
    osl_footer: Optional[LIMSDeviceFooter] = Field(
        {'osl_template': 'OslTemplate:KB/Device/Footer'}, title='LIMS/Device/Footer'
    )


class Entity(BaseModel):
    osl_template: Optional[str] = 'OslTemplate:KB/Entity'
    osl_template_label: Optional[str] = 'Entity'
    label: Optional[Union[str, List[str]]] = Field(None, title='Label')
    """
    Human readable name
    """
    label_lang_code: Optional[LangCode] = Field('en', title='Lang code')
    extensions: Optional[List[Device]] = Field(None, title='Extensions')
    osl_wikitext: Optional[str] = '=Details=\n'
    osl_footer: Optional[KBEntityFooter] = Field(
        {'osl_template': 'OslTemplate:KB/Entity/Footer'}, title='KB/Entity/Footer'
    )


Device.update_forward_refs()
