"""Dummy Prefect workflow that prints a message on an OSW page.

Usage (PowerShell):
    $env:PREFECT_API_URL="https://osw.example.com:4200/api"
    $env:PREFECT_PUBLIC_URL="https://osw.example.com/w/rest.php/apigateway/v1/prefect"
    $env:OSW_USER="Bot@name"
    $env:OSW_SERVER="osw.example.com"
    $env:OSW_PASSWORD="bot-password"
    python examples/prefect/hello_world.py

Usage (Bash):
    export PREFECT_API_URL="https://osw.example.com:4200/api"
    export PREFECT_PUBLIC_URL="https://osw.example.com/w/rest.php/apigateway/v1/prefect"
    export OSW_USER="Bot@name"
    export OSW_SERVER="osw.example.com"
    export OSW_PASSWORD="bot-password"
    python examples/prefect/hello_world.py

Environment variables:
    PREFECT_API_URL      Prefect server API URL (used by the worker)
    PREFECT_PUBLIC_URL   (optional) Public URL stored in PrefectFlow entity,
                         for use by browser clients (e.g. prefect.js).
                         Falls back to PREFECT_API_URL if not set.
    OSW_USER             OSW bot username
    OSW_SERVER           OSW instance domain
    OSW_PASSWORD         OSW bot password. If not set, falls back to a
                         Prefect Secret named <user>-<domain-with-dashes>.
"""

from typing import Optional
from uuid import UUID, uuid4

from opensemantic.base.v1 import Article
from prefect import flow, task
from pydantic.v1 import BaseModel, Field

import osw.model.entity as model
from osw.core import OSW
from osw.utils.workflow import (
    ConnectionSettings,
    DeployConfig,
    DeployParam,
    WorkflowRequest,
    connect,
    deploy,
)
from osw.wtsite import WtSite

# Module-level OSW instance, set by the connect_osw task
osw: Optional[OSW] = None


@task
def connect_osw(settings: Optional[ConnectionSettings] = None):
    """Initiates the connection to the OSW instance"""
    global osw
    osw = connect(settings)


@task
def fetch_schema():
    """Fetch custom schemas not yet available in packages.

    Software, PrefectFlow, and Article are already provided by
    opensemantic.base, so no fetch is needed for this example.
    Uncomment and adapt the code below if your workflow uses
    schemas that are only available on the OSW instance.
    """
    # osw.fetch_schema(
    #     OSW.FetchSchemaParam(
    #         schema_title=[
    #             "Category:OSW...",  # your custom category
    #         ],
    #         mode="replace",
    #     )
    # )


class Result(BaseModel):
    """The result dataclass"""

    uuid: Optional[UUID] = Field(default_factory=uuid4, title="UUID")
    """UUIDv4 of the result (autogenerated)"""
    target_title: Optional[str] = None
    """the target title to store the result.
    Autogenerated from uuid if not given
    """
    msg: str
    """The message you want to leave on the target page"""


@task
def store_and_document_result(result: Result):
    """Store workflow results on an OSW entry

    Parameters
    ----------
    result
        see Result dataclass
    """
    if result.target_title:
        title = result.target_title
    else:
        title = "Item:" + osw.get_osw_id(result.uuid)
    entity = osw.load_entity(
        OSW.LoadEntityParam(
            titles=[title],
            autofetch_schema=False,
            model_to_use=Article,
        )
    ).entities[0]
    if entity is None:
        # does not exist yet - create a new one
        entity = Article(
            uuid=result.uuid, label=[model.Label(text="Article for dummy workflow")]
        )

    # edit structured data
    entity = entity.cast(Article)
    entity.description = [model.Description(text="some descriptive text")]
    osw.store_entity(entity)

    # edit unstructured data (ToDo: access page directly from entity)
    page = osw.site.get_page(WtSite.GetPageParam(titles=[title])).pages[0]
    page.set_slot_content(
        slot_key="main", content=page.get_slot_content("main") + "<br>\n" + result.msg
    )
    page.edit()
    print("FINISHED")


class Request(WorkflowRequest):
    """Request for the dummy workflow."""

    msg: Optional[str] = "test message"
    """The message you want to leave on the target page"""


@flow(
    name="Dummy Workflow",
    description="Dummy workflow that prints a message on a target page",
)
def dummy_workflow(request: Request):
    """Dummy workflow that prints a message on a target page

    Parameters
    ----------
    request
        see Request dataclass
    """
    connect_osw(ConnectionSettings(osw_domain=request.osw_domain))
    fetch_schema()
    store_and_document_result(Result(msg=request.msg, target_title=request.subject))


if __name__ == "__main__":
    # Direct run: dummy_workflow(Request(msg="Test"))

    # Deploy and serve with OSW registration
    from os import environ

    osw_instance = connect()
    deploy(
        DeployParam(
            deployments=[
                DeployConfig(
                    flow=dummy_workflow,
                    name="Dummy Workflow Deployment",
                )
            ],
            osw=osw_instance,
            public_url=environ.get("PREFECT_PUBLIC_URL"),
        )
    )
